### ISSUE TITLE
Uitzendinggemist (NPO) error

### ISSUE THREAD

**Issue by Roelofpieter** [Opvolger/plugin.video.uzg#21]
Sinds gisteren krijg ik een foutmelding (Uitzendinggemist (NPO) error) bij het oproepen van een gemiste uitzending. Ik heb dit getest bij een nieuwe aflevering Keuringsdienst van waarde. Ook een oudere aflevering, die vorige week nog goed ging, speelde niet af. Ook een aflevering van "Kerkdiensten" (is een test hè) verscheen de melding en speelde de uitzending niet. In het log verschijnt de volgende melding. Speelt dit alleen bij mij?

```
22:07:55.839 T:1453310720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 158, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 139, in router
                                                play_video(params['whatson_id'])
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 123, in play_video
                                                play_item = xbmcgui.ListItem(path=uzg.get_play_url(whatson_id))
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 130, in get_play_url
                                                return self.npoHelpers.get_play_url(whatson_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 36, in get_play_url
                                                json_data = json.loads(data)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
22:07:56.239 T:1926292048   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uzg/?action=play&whatson_id=KN_1704077]
```

**Comment by Opvolger** [comment]
Welke versie gebruik je van mijn addon? Heb van de week een nieuwe gemaakt na een API wijziging van de NPO

**Comment by Roelofpieter** [comment]
Hé opvolger. Ja inderdaad, dat zal het zijn. Ik had wel de plugins gechecked op updates, maar het was me even ontschoten dat uzg niet meer via een repository aangeboden wordt (toch?). Ik zie nu ook dat de plugin nu alleen nog werkt op kodi 18. Dat is jammer voor mij: Ik draai osmc op mijn raspberry pi en die heeft (nog) kodi 17.6 . Een update naar 18 zit er aan te komen ("isn't far off"). Nog even volhouden voor mij dus. Bedakt voor je reactie

**Comment by gvlierop** [comment]
Beste Bas,
Ik had 5,= overgemakt voor je geweldige inzet. Wel bietje voor kopen ;)
Hoop dat meerdere volgen. 
Groetjes Geert.
