### ISSUE TITLE
Bij het starten van Uitzending gemist direct foutmelding: 

### ISSUE THREAD

**Issue by gvlierop** [Opvolger/plugin.video.uzg#29]
Tja, Bas eerst weken geen probleem en dat de een na de ander?
Vreemd, gisteren na installatie 3.4.1. nog geen probleem m.u.v. Filosofisch kwartet maar nu dus het gehele uitzendinggemist app. Zijn er gelijke reactie's of heeft mijn Kodi 18.1 de kuren gekregen? Kodi runt overigens op Android TV Box. 

Ben benieuwd ....

 Groetjes. Geert.

19-08-21 18:50:00.711 T:4174  NOTICE: starting zeroconf publishing
2019-08-21 18:50:00.712 T:4174  NOTICE: CWebServer[8080]: Started
2019-08-21 18:50:00.724 T:4578  NOTICE: ES: Starting UDP Event server on port 9777
2019-08-21 18:50:00.728 T:4578  NOTICE: UDP: Listening on port 9777 (ipv6 : true)
2019-08-21 18:50:05.477 T:4458   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.google.android.music.png
2019-08-21 18:50:05.519 T:4825   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.android.gallery3d.png
2019-08-21 18:50:05.587 T:4457   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.google.android.videos.png
2019-08-21 18:50:10.236 T:4458   ERROR: GetDirectory - Error getting
2019-08-21 18:50:10.443 T:5077   ERROR: Previous line repeats 6 times.
2019-08-21 18:50:10.443 T:5077   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named inputstreamhelper
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uzg/addon.py", line 14, in <module>
                                                import inputstreamhelper
                                            ImportError: No module named inputstreamhelper
                                            -->End of Python script error report<--
2019-08-21 18:50:10.462 T:5076   ERROR: GetDirectory - Error getting plugin://plugin.video.uzg/
2019-08-21 18:50:10.483 T:4174   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/) failed
2019-08-21 18:50:17.860 T:4174   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-08-21 18:50:17.969 T:5222   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named inputstreamhelper
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.uzg/addon.py", line 14, in <module>
                                                import inputstreamhelper
                                            ImportError: No module named inputstreamhelper
                                            -->End of Python script error report<--
2019-08-21 18:50:17.976 T:5221   ERROR: GetDirectory - Error getting plugin://plugin.video.uzg/?action=episodes&link=https%3a%2f%2fstart-api.npo.nl%2fpage%2ffranchise%2fKN_1676589
2019-08-21 18:50:17.980 T:4174   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/?action=episodes&link=https%3a%2f%2fstart-api.npo.nl%2fpage%2ffranchise%2fKN_1676589) failed
2019-08-21 18:55:23.190 T:4231  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2019-08-21 18:55:23.198 T:4231  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 3770 m_frameSize: 8 channels: 2

**Comment by gvlierop** [comment]
Vreemd, zojuist versie 3.4.0 terug gezet en het werkt weer ;) Zelfs nu ook het Filosofisch Kwartet weer. Snap er niks van maar ben blij toe.

Opgelost voor mij maar ook voor 3.4.1.?
