### ISSUE TITLE
Seems like a bug  on OSMC installation since latest version.. mem leak?

### ISSUE THREAD

**Issue by RicardoIsNotAvailable** [Opvolger/plugin.video.uzg#31]
after some time playing playback freezes up. part of log:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 191, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 182, in router
                                                play_video(params['whatson_id'])
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/addon.py", line 153, in play_video
                                                stream_info = uzg.get_play_url(whatson_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 67, in get_play_url
                                                return self.npoHelpers.get_play_url(whatson_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 43, in get_play_url
                                                url, NpoHelpers.__get_video_request_data('dash'))
                                              File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 24, in get_json_data
                                                response = urlopen(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--

**Comment by Opvolger** [comment]
URLError: <urlopen error [Errno -2] Name or service not known>

kortom, python kon even niet de dns ophalen van de nop streaming site. Dit kan gebeuren als je DNS-server een hik-up had of dat er een probleem was bij de npo streaming site
