### ISSUE TITLE
Foutmelding bij het openen van een "letter"

### ISSUE THREAD

**Issue by jonkerj** [Opvolger/plugin.video.uzg#32]
Als ik in kodi/uzg op een letter klik (in mijn geval de "E") in het hoofdmenu, krijg ik een error die me naar de logs verwijst. Daar lees ik dit:

```
2019-10-09 19:22:30.106 T:140039512135424 WARNING: Previous line repeats 2 times.
2019-10-09 19:22:30.106 T:140039512135424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 191, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 176, in router
                                                list_letter(params['letter'])
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 93, in list_letter
                                                franchises = _cache.cacheFunction(uzg.getAZPage, letter)
                                              File "/storage/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 25, in getAZPage
                                                return SerieItems('https://start-api.npo.nl/media/series?az=' + letter).uzgitemlist
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 113, in __init__
                                                json = self.npoHelpers.get_json_data(url)
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 24, in get_json_data
                                                response = urlopen(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
2019-10-09 19:22:30.315 T:140039503742720   ERROR: GetDirectory - Error getting plugin://plugin.video.uzg/?action=letter&letter=E
2019-10-09 19:22:30.321 T:140041027258496   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/?action=letter&letter=E) failed
```

Voor het gemak even de stacktrace zonder indenting:
```
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 191, in <module>
    router(sys.argv[2][1:])
  File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 176, in router
    list_letter(params['letter'])
  File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 93, in list_letter
    franchises = _cache.cacheFunction(uzg.getAZPage, letter)
  File "/storage/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
    ret_val = funct(*args)
  File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 25, in getAZPage
    return SerieItems('https://start-api.npo.nl/media/series?az=' + letter).uzgitemlist
  File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 113, in __init__
    json = self.npoHelpers.get_json_data(url)
  File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 24, in get_json_data
    response = urlopen(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 403: Forbidden
-->End of Python script error report<--
```

Na een reboot van het systeem in kwestie krijg ik exact dezelfde melding. Ik ben nog niet zover gegaan om in de code te graven, maar ik vermoed dat ze bij NPO wat hebben omgegooid.

Ik gebruik plugin 3.4.1 (laatste release op dit moment) onder LibreELEC 9.1.501 (Kodi 18.4).

**Comment by Opvolger** [comment]
klopt, dit zie ik nu ook, werd ook al aan gesproken op de chat.

Ze hebben de api-key aangepast, dus ik moet op jacht naar een nieuwe.

**Comment by Opvolger** [comment]
het was even zoeken, maar het werkt weer. nu kan ik thuis het nieuws weer kijken!
