### ISSUE TITLE
Plugin kan lijst met programma's niet ophalen 

### ISSUE THREAD

**Issue by jhaand** [Opvolger/plugin.video.uzg#36]
Sinds vanavond werkt de uzg plugin niet meer. De app onder Android doet het nog wel. 

Ik draai Libreelec 9.0.2 met Kodi: 18.2 en de uzg plugin 3.4.2 op een Odroid C-2. 

De kodi.log als ik op een letter klik bij UZG. 
```
2020-03-19 18:31:45.025 T:3678606192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'original'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 191, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 176, in router
                                                list_letter(params['letter'])
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 93, in list_letter
                                                franchises = _cache.cacheFunction(uzg.getAZPage, letter)
                                              File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 623, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 25, in getAZPage
                                                return SerieItems('https://start-api.npo.nl/media/series?az=' + letter).uzgitemlist
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 117, in __init__
                                                self.uzgitemlist = self.__get_items(json)
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 133, in __get_items
                                                image = NpoHelpers.get_image(serie)
                                              File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 64, in get_image
                                                if item['images'] and item['images']['original']:
                                            KeyError: 'original'
                                            -->End of Python script error report<--
2020-03-19 18:31:45.154 T:3965711216   ERROR: GetDirectory - Error getting plugin://plugin.video.uzg/?action=letter&letter=I
2020-03-19 18:31:45.156 T:4093829920   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/?action=letter&letter=I) failed
```
De uzgtest file zegt hetzelfde.

**Comment by Opvolger** [comment]
Ik ervaar het zelfde. Ze zullen wel de API hebben veranderd en de oud welke in nog gebruikte uitgezet. Zal er naar gaan kijken. Maar ben erg druk met werk momenteel. Deze coronavirus zorgt ook voor veel ict-werk :)

**Comment by johan-adriaans** [comment]
Probleem gevonden, hier een pull request: https://github.com/Opvolger/plugin.video.uzg/pull/37

De images array heeft een nieuwe layout gekregen met allerhande devices en allemaal dezelfde afbeeldingen ;) Ik heb grid.tile maar gekozen.

Ik kon item[broadcasters] niet testen met inhoud omdat ik die nooit gevuld terug kreeg, maar met slag om de arm is het zo gefixt :)

**Comment by johan-adriaans** [comment]
Voor de gebruiker die niet kan wachten, je kan deze file (resources/lib/npoapihelpers.py) overschrijven met deze content: https://github.com/johan-adriaans/plugin.video.uzg/blob/fix-programma-overzicht-image-bug/resources/lib/npoapihelpers.py

In het pull request kun je zien wat er is veranderd: https://github.com/Opvolger/plugin.video.uzg/pull/37

**Comment by djvl** [comment]
Thanks @johan-adriaans, kan bevestigen dat het weer werkt met je voorgestelde wijziging.

**Comment by gvlierop** [comment]
Johan Hartelijk bedankt voor je inbreng en moeite om wijziging in afwachting van Bas reeds beschikbaar te maken!!  Bas, sterkte met de drukke ICT-werkzaamheden !!

**Comment by jhaand** [comment]
Merci @johan-adriaans. UZG werkt weer.

**Comment by Opvolger** [comment]
Hier ook weer. zal nog naar de pull request kijken, maar had lokaal al aanpassingen gemaakt.

**Comment by jakenl** [comment]
Bedankt mannen. Ik heb ondertussen geleerd: als uitzendiggemist niet werkt: gelijk hier even op github kijken. En zo waar, de update stond al klaar!

Klasse!
