### ISSUE TITLE
Vernieuwde NPO Start

### ISSUE THREAD

**Issue by oegstgeest** [Opvolger/plugin.video.uzg#53]
Ik las dat de site van NPO Start wordt vernieuwd.
Zijn er plannen om deze plugin ook bij te werken, of moet ik op zoek naar iets anders (want ik gebruik deze plugin regelmatig)?

**Comment by Opvolger** [comment]
Ik hoop dat alles blijft werken, als dat niet zo is heb ik wat te doen. Ik gebruik de addon zelf ook nog steeds. Voor de kinderen om klokhuis enz terug te kijken. Dus ik zal het proberen weer aan de praat te krijgen :). Zal niet gelijk op 1 dec. zijn, ik heb ook een privé leven :)

**Comment by M4rc3lv** [comment]
Yep, het is 1 december, hij is stuk. Vervelend dat ze dit net nu in deze drukke maand doen.

**Comment by ComputerBoer** [comment]
Ik heb even wat rond gezocht op de nieuwe website en heb een lijstje met api's gemaakt waarmee we volgens mij alles weer aardig kunnen opbouwen. Ze hebben wel ook alle classes omgegooid dus die moeten ook worden bijgewerkt.

Zoeken op serie: 
`GET: https://npo.nl/start/api/domain/search-results?query=lubach&searchType=series&subscriptionType=anonymous`
Seizoenen van serie ophalen:
`GET: https://npo.nl/start/api/domain/series-seasons?slug=de-avondshow-met-arjen-lubach`
Afleveringen van seizoen ophalen:
`GET: https://npo.nl/start/api/domain/programs-by-season?guid=2b9f2a98-a1b3-447c-8c8b-55da536ce6e2`
Alle kanalen ophalen:
`GET: https://npo.nl/start/api/domain/guide-channels`

Om de streaming link van een aflevering op te halen moet je eerst een post doen voor een token. Hierin zit een object met de property `productId` met waarde de `productId` van een aflevering of een `externalId` van een kanaal. 
`POST: https://npo.nl/start/api/domain/player-token`

Daar krijg je een token van terug die je in de `Authorization` header moet zetten bij de post voor de stream link.
`POST: https://prod.npoplayer.nl/stream-link`

Deze post moet verder de volgende body hebben voor een aflevering:
`{
    "profileName": "dash",
    "drmType": "widevine",
    "referrerUrl": "https://npo.nl/start/serie/{{aflevering.series.slug}}/{{aflevering.season.slug}}/{{aflevering.slug}}/afspelen"
}`

Alle variabele data wordt opgehaald bij het ophalen van de afleveringen voor een seizoen.
De `referrerUrl` voor een live kanaal is de volgende: `https://npo.nl/start/live?channel={{channel.title}}`
Zowel de externalid als de kanaaltitel van een live kanaal worden opgehaald bij de guide-channels call

**Comment by Frambozentaart** [comment]
@Opvolger en Bas, Ik gebruik UZG en Retospect. Retrospect voor NPO+ abo en UZG omdat ik NPO1;2;3 en de extra's, bij bladwijzers kan zetten, waarmee ik dan ook de Raspberrypi en de tv kan opstarten. Blijvende bladwijzers voor Retrospect aanmaken lukt mij niet en ik heb al eens bij "Bas Rieter" gelezen dat, dat ook niet gaat lukken. Tot 1 december werkte, UZG, uitstekend, maar helaas.
Door alle crashende addons, meestal veroorzaakt door wijzigingen bij Google heb ik al aardig wat geleerd over Kodi en ga mij nog verdiepen in scripting. Zodra er een fix of een nieuw versie is, probeer ik die onmiddelijk uit, net als ik dat bij de laatste versie van Retrospect heb gedaan.
Ik zal mijn bevindingen dan ook nu niet meer op het kodi-forum melden maar bij het betreffende item op Github. zie dat als mijn bijdrage. Er is een periode geweest dat het me niet lukte een account aan te maken vandaar, dat ik hier steeds via een van de leden, van het kodi-forum terecht kwam. Als het Opvolger" niet mocht lukken, dan toch hartelijk dank voor jouw handige addon. Bij LibreElec staat altijd "just enough OS for KODI", ik zou willen zeggen "UZG just enough kodi for NPO"

**Comment by Opvolger** [comment]
Om het ingewikkeld te houden @basrieter en ik hebben allebei de voornaam Bas :)

Zie al een pull-request klaar staan wat al heet een en ander fixxed. Zal mogelijk van het weekend worden dat ik daarna ga kijken. Zo eerst pakjesavond vieren met de kinderen.

**Comment by Opvolger** [comment]
Versie 4.0.0 is er bij, code totaal herschreven. koste even wat moeite, helaas 1 api code welke ding ik alleen voor de website is moeten gebruiken. hoop dat die nog een tijdej blijft bestaan en blijft werken.

Hier en daar zzag ik net op de tv nog een error, zal er binnenkort nog eens voor gaan zitten.

**Comment by ArthurBorsboom** [comment]
Ik heb v4.0.0 geprobeerd en NPO1 lijkt weer te werken; ik heb niet meer getest dan dat.
Tevens heb ik een kleine donatie gedaan, highly overdue, but better late than never.

**Comment by averaart** [comment]
Hoi @Opvolger!

Dank voor alle effort weer! Helaas wil ie bij mij niet starten. Ik heb 4.0.0 gedownload en vervolgens "Install from zipfile" gebruikt, waarbij Kodi leek te herkennen dat het om een update ging.

Helaas wil de Addon vervolgens niet starten met een redelijk nietszeggende opmerking in beeld. (Ook niet na reboot)

Hierbij wel een stuk logging. Enig idee wat ik eventueel nog mis of verkeerd doe?
Kan ik nog andere info aanleveren?

```
2023-12-10 16:30:24.865 T:863     DEBUG <general>: ------ Window Deinit (Home.xml) ------
2023-12-10 16:30:24.865 T:863     DEBUG <general>: FreeVisualisation() done
2023-12-10 16:30:24.880 T:863     DEBUG <general>: ------ Window Init (MyVideoNav.xml) ------
2023-12-10 16:30:24.904 T:863     ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
2023-12-10 16:30:24.940 T:863     DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.uzg/)
2023-12-10 16:30:24.940 T:863     DEBUG <general>:   ParentPath = [plugin://plugin.video.uzg/]
2023-12-10 16:30:24.941 T:1038    DEBUG <general>: Thread waiting start, auto delete: false
2023-12-10 16:30:24.947 T:1034    DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.uzg] took 7 ms
2023-12-10 16:30:24.947 T:1038    DEBUG <general>: StartScript - calling plugin NPO Start('plugin://plugin.video.uzg/','4','','resume:false')
2023-12-10 16:30:24.947 T:1039    DEBUG <general>: Thread JobWorker start, auto delete: true
2023-12-10 16:30:24.948 T:1040    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2023-12-10 16:30:24.948 T:1040     INFO <general>: initializing python engine.
2023-12-10 16:30:24.948 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): start processing
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: -->Python Interpreter Initialized<--
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: 
                                                   
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): the source file to load is "/storage/.kodi/addons/plugin.video.uzg/addon.py"
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): setting the Python path to /storage/.kodi/addons/plugin.video.uzg:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.pysocks/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/lib/python3.8/site-packages
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): entering source directory /storage/.kodi/addons/plugin.video.uzg
2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): instantiating addon using automatically obtained id of "plugin.video.uzg" dependent on version 0.0.0 of the xbmc.python api
2023-12-10 16:30:25.041 T:863     DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2023-12-10 16:30:25.204 T:1040    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 15, in <module>
                                                       from resources.lib.uzg import Uzg
                                                     File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 11, in <module>
                                                       from resources.lib.npoapiclasses import AddonItems, QueryItems, SeasonItems, Channels, SeasonItems, EpisodesOfSeasonItems, EpisodesOfSerieItems, AllItems, CollectionItems
                                                     File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 64, in <module>
                                                       class EpisodesOfSerieItems(object):
                                                     File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 68, in EpisodesOfSerieItems
                                                       def getItems(self) -> list[AddonItems]:
                                                   TypeError: 'type' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2023-12-10 16:30:25.204 T:1040    DEBUG <general>: onExecutionDone(12, /storage/.kodi/addons/plugin.video.uzg/addon.py)
2023-12-10 16:30:25.221 T:863     DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2023-12-10 16:30:25.497 T:1040     INFO <general>: Python interpreter stopped
2023-12-10 16:30:25.497 T:1040    DEBUG <general>: Thread LanguageInvoker 3530158720 terminating
2023-12-10 16:30:25.511 T:1038    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.uzg/
2023-12-10 16:30:25.511 T:1038    DEBUG <general>: Thread waiting 3868189312 terminating
2023-12-10 16:30:25.520 T:863     DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-12-10 16:30:25.520 T:863     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/) failed
2023-12-10 16:30:25.521 T:863     DEBUG <general>: CGUIMediaWindow::GetDirectory ()
2023-12-10 16:30:25.521 T:863     DEBUG <general>:   ParentPath = [plugin://plugin.video.uzg/]
2023-12-10 16:30:25.528 T:1041    DEBUG <general>: Thread waiting start, auto delete: false
2023-12-10 16:30:25.533 T:1041    DEBUG <general>: Thread waiting 3868189312 terminating
2023-12-10 16:30:25.557 T:1042    DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2023-12-10 16:30:25.564 T:1042    DEBUG <general>: Thread BackgroundLoader 3564069504 terminating
2023-12-10 16:30:30.935 T:1043    DEBUG <CWebserver[8080]>: request received for /jsonrpc
2023-12-10 16:30:31.667 T:863     DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2023-12-10 16:30:35.576 T:908     DEBUG <general>: EventClient: button name "back" map "R1" pressed
2023-12-10 16:30:35.580 T:863     DEBUG <general>: HandleKey: menu (0xd8) pressed, action is Back
2023-12-10 16:30:35.580 T:863     DEBUG <general>: CGUIWindowManager::PreviousWindow: Deactivate
2023-12-10 16:30:36.187 T:863     DEBUG <general>: ------ Window Deinit (MyVideoNav.xml) ------
2023-12-10 16:30:36.189 T:863     DEBUG <general>: FreeVisualisation() done
```

**Comment by M4rc3lv** [comment]
Bij 4.0.1 kreeg ik hetzelfde :-(
Ik ben wel heel blij dat er aan gewerkt wordt.

**Comment by M4rc3lv** [comment]
Ik heb de add-on en de instellingen helemaal verwijderd en daarna via zip-bestand 4.0.1 geinstalleerd, en dan kreeg ik vergelijkbare fout als Andra.

**Comment by Opvolger** [comment]
Mogelijk gebruiken jullie nog Kodi 19 en heb ik te nieuwe annotatie gebruikt in Python. Zal (niet vandaag meer denk ik) binnenkort dat vervangen. Dan zal het weer moeten werken op Kodi 19

**Comment by M4rc3lv** [comment]
Ja dat was het in mijn geval, ik had een oudere versie van Kodi. Na het update naar 20.x werkt 4.0.1 heel erg goed. Mijn dank is groot!

**Comment by sprintv** [comment]
Bas, allereerst bedankt voor alle moeite die je weer in de plugin gestopt hebt.
Helaas krijg ik versie 4.0.1 (nog) niet aan de praat. Ik gebruik hem op een RPi 3 met Kodi 18.9 Leia en op een Microsoft Surface met Kodi 20.2 Nexus. Ik begrijp dat het voor Kodi 18.9 aan de python versie ligt, maar ik krijg hem, in tegenstelling tot M4rc3lv, ook niet op Kodi 20.2 aan de praat. Ik heb op beide apparaten eerst de oude plugin verwijderd, versie 4.0.1 geïnstalleerd en een reboot uitgevoerd. Enig idee waar dat aan zou kunnen liggen?

**Comment by harmenkets** [comment]
@sprintv Meestal staat in de logging wel een aanwijzing. Ik neem aan dat je Surface op Windows draait? Dan zou de log op de volgende plek moeten staan geloof ik:
C:\Users\%username%\AppData\Roaming\Kodi\kodi.log

**Comment by sprintv** [comment]
@harmenkets De Surface draait inderdaad op Windows 10. Dit is wat er gelogd wordt wanneer ik uzg probeer te starten:

2023-12-11 13:20:45.172 T:10508   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-12-11 13:20:47.422 T:9020    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\sprin\AppData\Roaming\Kodi\addons\plugin.video.uzg\addon.py", line 15, in <module>
                                                       from resources.lib.uzg import Uzg
                                                     File "C:\Users\sprin\AppData\Roaming\Kodi\addons\plugin.video.uzg\resources\lib\uzg.py", line 11, in <module>
                                                       from resources.lib.npoapiclasses import AddonItems, QueryItems, SeasonItems, Channels, SeasonItems, EpisodesOfSeasonItems, EpisodesOfSerieItems, AllItems, CollectionItems
                                                     File "C:\Users\sprin\AppData\Roaming\Kodi\addons\plugin.video.uzg\resources\lib\npoapiclasses.py", line 77, in <module>
                                                       class EpisodesOfSerieItems(object):
                                                     File "C:\Users\sprin\AppData\Roaming\Kodi\addons\plugin.video.uzg\resources\lib\npoapiclasses.py", line 81, in EpisodesOfSerieItems
                                                       def getItems(self) -> list[AddonItems]:
                                                   TypeError: 'type' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2023-12-11 13:20:47.433 T:3660     info <general>: CActiveAESink::OpenSink - initialize sink
2023-12-11 13:20:47.674 T:4780    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.uzg/
2023-12-11 13:20:47.683 T:10508   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/) failed

Het zegt mij helaas niet zo veel :-(

**Comment by Frambozentaart** [comment]
@Bas Bedankt voor het vele werk wat je er weer ingestoken hebt. 4.01 werk bij mij weer goed.
De bladwijzers krijgen echter geen icoon/thumb(nail). Dat heb ik in favourites.xml aangepast door de hyperlink van de vorige versie erbij te plakken dat ziet er als volgt uit
![Tonshot 915](https://github.com/Opvolger/plugin.video.uzg/assets/152975644/0e87430b-fa46-49ad-90bb-236e75953403)
Mind you, dat Zapp geen plaatje had die ik er zelf bij gezocht heb en in “/storage/downloads”
heb gezet  De x-stra’s heb ik net zo aangepast. Ik ben blij dat het weer werkt.
Dit is niet mijn volledige favorieten lijst, maar alleen voorbeeld hoe je te werk kan gaan, als je icoontjes bij de verschillende zenders wil hebben, een soort workarround.

**Comment by harmenkets** [comment]
@sprintv Ik ben helaas ook geen python held, maar de foutmelding ziet er hetzelfde uit  als degene die averaart eerder postte (echter wel wat andere line nrs).

Misschien ff een versie afwachten waarin de Bas de niet ondersteunde annotatie heeft vervangen/geadresseerd.

**Comment by Letalis82** [comment]
> Hoi @Opvolger!
> 
> Dank voor alle effort weer! Helaas wil ie bij mij niet starten. Ik heb 4.0.0 gedownload en vervolgens "Install from zipfile" gebruikt, waarbij Kodi leek te herkennen dat het om een update ging.
> 
> Helaas wil de Addon vervolgens niet starten met een redelijk nietszeggende opmerking in beeld. (Ook niet na reboot)
> 
> Hierbij wel een stuk logging. Enig idee wat ik eventueel nog mis of verkeerd doe? Kan ik nog andere info aanleveren?
> 
> ```
> 2023-12-10 16:30:24.865 T:863     DEBUG <general>: ------ Window Deinit (Home.xml) ------
> 2023-12-10 16:30:24.865 T:863     DEBUG <general>: FreeVisualisation() done
> 2023-12-10 16:30:24.880 T:863     DEBUG <general>: ------ Window Init (MyVideoNav.xml) ------
> 2023-12-10 16:30:24.904 T:863     ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
> 2023-12-10 16:30:24.940 T:863     DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.uzg/)
> 2023-12-10 16:30:24.940 T:863     DEBUG <general>:   ParentPath = [plugin://plugin.video.uzg/]
> 2023-12-10 16:30:24.941 T:1038    DEBUG <general>: Thread waiting start, auto delete: false
> 2023-12-10 16:30:24.947 T:1034    DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.uzg] took 7 ms
> 2023-12-10 16:30:24.947 T:1038    DEBUG <general>: StartScript - calling plugin NPO Start('plugin://plugin.video.uzg/','4','','resume:false')
> 2023-12-10 16:30:24.947 T:1039    DEBUG <general>: Thread JobWorker start, auto delete: true
> 2023-12-10 16:30:24.948 T:1040    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
> 2023-12-10 16:30:24.948 T:1040     INFO <general>: initializing python engine.
> 2023-12-10 16:30:24.948 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): start processing
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: -->Python Interpreter Initialized<--
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: 
>                                                    
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): the source file to load is "/storage/.kodi/addons/plugin.video.uzg/addon.py"
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): setting the Python path to /storage/.kodi/addons/plugin.video.uzg:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.pysocks/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/lib/python3.8/site-packages
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): entering source directory /storage/.kodi/addons/plugin.video.uzg
> 2023-12-10 16:30:24.977 T:1040    DEBUG <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.uzg/addon.py): instantiating addon using automatically obtained id of "plugin.video.uzg" dependent on version 0.0.0 of the xbmc.python api
> 2023-12-10 16:30:25.041 T:863     DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
> 2023-12-10 16:30:25.204 T:1040    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: 'type' object is not subscriptable
>                                                    Traceback (most recent call last):
>                                                      File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 15, in <module>
>                                                        from resources.lib.uzg import Uzg
>                                                      File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 11, in <module>
>                                                        from resources.lib.npoapiclasses import AddonItems, QueryItems, SeasonItems, Channels, SeasonItems, EpisodesOfSeasonItems, EpisodesOfSerieItems, AllItems, CollectionItems
>                                                      File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 64, in <module>
>                                                        class EpisodesOfSerieItems(object):
>                                                      File "/storage/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 68, in EpisodesOfSerieItems
>                                                        def getItems(self) -> list[AddonItems]:
>                                                    TypeError: 'type' object is not subscriptable
>                                                    -->End of Python script error report<--
>                                                    
> 2023-12-10 16:30:25.204 T:1040    DEBUG <general>: onExecutionDone(12, /storage/.kodi/addons/plugin.video.uzg/addon.py)
> 2023-12-10 16:30:25.221 T:863     DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
> 2023-12-10 16:30:25.497 T:1040     INFO <general>: Python interpreter stopped
> 2023-12-10 16:30:25.497 T:1040    DEBUG <general>: Thread LanguageInvoker 3530158720 terminating
> 2023-12-10 16:30:25.511 T:1038    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.uzg/
> 2023-12-10 16:30:25.511 T:1038    DEBUG <general>: Thread waiting 3868189312 terminating
> 2023-12-10 16:30:25.520 T:863     DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
> 2023-12-10 16:30:25.520 T:863     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/) failed
> 2023-12-10 16:30:25.521 T:863     DEBUG <general>: CGUIMediaWindow::GetDirectory ()
> 2023-12-10 16:30:25.521 T:863     DEBUG <general>:   ParentPath = [plugin://plugin.video.uzg/]
> 2023-12-10 16:30:25.528 T:1041    DEBUG <general>: Thread waiting start, auto delete: false
> 2023-12-10 16:30:25.533 T:1041    DEBUG <general>: Thread waiting 3868189312 terminating
> 2023-12-10 16:30:25.557 T:1042    DEBUG <general>: Thread BackgroundLoader start, auto delete: false
> 2023-12-10 16:30:25.564 T:1042    DEBUG <general>: Thread BackgroundLoader 3564069504 terminating
> 2023-12-10 16:30:30.935 T:1043    DEBUG <CWebserver[8080]>: request received for /jsonrpc
> 2023-12-10 16:30:31.667 T:863     DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
> 2023-12-10 16:30:35.576 T:908     DEBUG <general>: EventClient: button name "back" map "R1" pressed
> 2023-12-10 16:30:35.580 T:863     DEBUG <general>: HandleKey: menu (0xd8) pressed, action is Back
> 2023-12-10 16:30:35.580 T:863     DEBUG <general>: CGUIWindowManager::PreviousWindow: Deactivate
> 2023-12-10 16:30:36.187 T:863     DEBUG <general>: ------ Window Deinit (MyVideoNav.xml) ------
> 2023-12-10 16:30:36.189 T:863     DEBUG <general>: FreeVisualisation() done
> ```

Heb helaas ook de zelfde probleem. Bij starten plugin kom ik niet verder.

Win 10
Kodi 20.2
Utg 4.0.1

**Comment by sprintv** [comment]
@Opvolger Nogmaals bedankt voor al het werk aan de vernieuwde plugin. Blijkbaar zijn er meer mensen die problemen hebben met UZG 4.0.1 in combinatie met Windows 10 en Kodi 20.2. helaas. Degene bij wie het wel werkt zullen een RPi of soortgelijk apparaat met Kodi 20.2 gebruiken neem ik aan. Wellicht zou je daar nog eens naar kunnen kijken. Momenteel heb ik alleen een RPi 3 met Kodi 18.9 en daar werkt het niet op. Kodi 20.2 werkt op en RPi 3 niet goed heb ik begrepen. Ik zal ondertussen zorgen dat je wat biertjes kunt drinken :-)

**Comment by ArthurBorsboom** [comment]
Mogelijk helpt het om een patroon te herkennen.
Hierbij enkele componenten van een werkende setup.

- OS: Arch Linux (kernel 6.6.5)
- Kodi: 20.2
- Python: 3.11.6
- plugin.video.uzg: 4.0.0

**Comment by sprintv** [comment]
@Opvolger Ik las op het Kodi forum dat Kodi voor Windows momenteel geleverd wordt met python 3.8.15. Dat zou goed de verklaring kunnen zijn voor de problemen op Windows systemen. Ik begrijp dat je op een gegeven moment de nieuwe python annotatie wilt gaan vervangen t.b.v. Kodi 19. Wellicht lost dat dan ook de Windows issues op.

**Comment by Opvolger** [comment]
Ik heb het nu weer gemaakt dat het zou moeten werken op Kodi 19 en dus ook python 3.8.x

Dus wens jullie allemaal succes met versie 4.0.2 :)

**Comment by sprintv** [comment]
@Opvolger Geweldig Bas. 4.0.2 werkt heel goed op Kodi voor Windows. Op de RPi 3 met Kodi 18.9 natuurlijk niet. Ik zal daarvoor een RPi 4 met Kodi 20.x in moet richten. Bedankt voor al het werk.

**Comment by averaart** [comment]
Hoi @Opvolger!

Ook ik kan bevestigen dat ie weer werkt op RPi 4 met LibreElec 10, Kodi 19.

Bedankt!

**Comment by sprintv** [comment]
@Opvolger Hoi Bas, Ik zag dat je weer een nieuwe versie (4.0.3) klaargezet had en hoopte dat het ook op mijn RPi 3 met Kodi 18.9 (Libreelec 9.2.6) zou werken, maar helaas. Ik krijg onderstaande melding:

2023-12-19 14:36:46.968 T:1936714176   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2023-12-19 14:36:47.693 T:1461678976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned
 the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (addon.py, line 58)
                                              File "/storage/.kodi/addons/plugin.video.uzg/addon.py", line 58
                                                def addItems(addonitems: List[AddonItems], action):
                                                                       ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--
2023-12-19 14:36:47.706 T:1471046528   ERROR: GetDirectory - Error getting plugin://plugin.video.uzg/
2023-12-19 14:36:47.707 T:1936714176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/) failed
2023-12-19 14:37:56.777 T:1653990272  NOTICE: ES: Client  from ::ffff:192.168.2.14 timed out
2023-12-19 14:38:12.844 T:1936714176  NOTICE: Samba is idle. Closing the remaining connections

Zou dat nog te fixen zijn?

**Comment by Frambozentaart** [comment]
@Bas² sinds gisteren 21-10-'24 geen NPO meer met UZG, noch met Retrospect

**Comment by ArthurBorsboom** [comment]
Same here...

```
2024-10-23 12:15:24.127 T:619      info <general>: VPN Mgr : VPN is started on /var/lib/kodi/.kodi/addons/service.vpn.manager/Mullvad/Netherlands (UDP).ovpn requesting 
2024-10-23 12:15:24.218 T:98171   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'token'
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 117, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 104, in router
                                                       playVideo(params['productId'])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 80, in playVideo
                                                       stream_info, licenseKey = Uzg.getPlayInfo(productId)
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 26, in getPlayInfo
                                                       token = NpoHelpers.getToken(externalId)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 98, in getToken
                                                       return json.loads(link)['token']
                                                              ~~~~~~~~~~~~~~~~^^^^^^^^^
                                                   KeyError: 'token'
                                                   -->End of Python script error report<--
                                                   
2024-10-23 12:15:24.285 T:497     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uzg/?action=play&productId=LI_NL1_4188102&guid=83dc1f25-a065-496c-9418-bd5c60dfb36d&slug=None]
```
