### ISSUE TITLE
NPO Plus content geeft 402 (Payment required) error

### ISSUE THREAD

**Issue by harmenkets** [Opvolger/plugin.video.uzg#56]
Allereerst heel erg bedankt voor het blijven ondersteunen/fixen van de plugin bij de API veranderingen van NPO start!! :+1: 

Ik liep bij bekijken van (wat later bleek) NPO Plus content aan tegen een plugin error.
Uit de logging blijkt dat er een 402 (Payment required) terugkomt, op zich logisch natuurlijk. Ik weet niet of dit door de API aanpassingen komt of dat de plugin altijd al zo heeft gewerkt, maar het viel me nu op.

Misschien kan de NPO Plus content weggefilterd worden of een melding getoond worden dat deze content niet/alleen met een abonnement bekeken kan worden?

Plugin versie: 4.0.1
Kodi versie: 20.2
Python versie: 3.11.6

Kodi logging:

```python
2023-12-11 16:04:52.355 T:187321   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uzg/?action=play&productId=POW_05789923&guid=2e0dbe46-73c5-4b45-8e00-1ce4b3e110df&slug=eigen-volk-eerst_3]
2023-12-11 16:05:32.361 T:213662   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 402: Payment Required
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 115, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 102, in router
                                                       playVideo(params['productId'])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 79, in playVideo
                                                       stream_info, licenseKey = Uzg.getPlayInfo(productId)
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 18, in getPlayInfo
                                                       info = NpoHelpers.getStream(token)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 52, in getStream
                                                       response = urlopen(req, data.toJSON().encode('utf-8'))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                       return opener.open(url, data, timeout)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 525, in open
                                                       response = meth(req, response)
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
                                                       response = self.parent.error(
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 563, in error
                                                       return self._call_chain(*args)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                       result = func(*args)
                                                                ^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 402: Payment Required
                                                   -->End of Python script error report<--
```

**Comment by orthello** [comment]
Voor hen die tegen problemen aan lopen... hou er rekening mee dat bookmarks/favorieten/bladwijzers/whatever naar UZG content niet meer werken en dus voor fouten/foutmeldingen kunnen zorgen. Loop je tegen problemen aan probeer dan eerst de hele route handmatig te doorlopen.

**Comment by Opvolger** [comment]
Ik dacht dat ik hier al wat voor had ingebouwd. Wat probeerde je te kijken? dan kan ik het na spelen.

ik had bij de films alle betaalde films er al uitgefilterd, blijkbaar mis ik ergens anders dit nog.

**Comment by harmenkets** [comment]
Bovenstaande log was van de 3e aflevering van 'Eigen Volk Eerst'; omdat die gisteren is uitgezonden speelt die nu wel gewoon af. Er staat ook al een aflevering 4 klaar (die volgende week wordt uitgezonden) en die geeft nog wel een 402.

**Comment by Opvolger** [comment]
Als het goed is, is dit nu opgelost

**Comment by harmenkets** [comment]
Yup, toekomstige aflevering staat er niet meer tussen. Nogmaals, bedankt voor alle energie/vrije tijd die je hier insteekt! :+1:

**Comment by atreyuhere** [comment]
Heel veel dank voor je inspanningen na de veranderingen op npo start. Ik gebruik de addon heel regelmatig, dus fixed zijn zeer gewaardeerd!

**Comment by harmenkets** [comment]
@Opvolger Ik denk dat ik toch nog een bug ben tegengekomen die met deze fix is meegekomen. Als ik zoek op 'pointer' (geeft als het goed is 1 resultaat) en die selecteer, krijg ik de volgende error:
```Python
2023-12-18 10:15:20.477 T:738135   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '<=' not supported between instances of 'int' and 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 116, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 106, in router
                                                       items = uzg.getItems(params['action'], params['guid'], params['productId'], params['slug'], text)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 47, in getItems
                                                       return self.episodesOfSeasonItems.getItems(guid)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 121, in getItems
                                                       return JsonToItems.getItems(NpoHelpers.getJsonData(url))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 62, in getItems
                                                       if restriction['available']['from'] <= now <= restriction['available']['till']:
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '<=' not supported between instances of 'int' and 'NoneType'
                                                   -->End of Python script error report<--
                                                   
2023-12-18 10:15:20.512 T:738134   error <general>: GetDirectory - Error getting plugin://plugin.video.uzg/?action=episodesSeason&guid=5d70638e-1a9b-4f34-a890-276f4750ed4d&productId=None&slug=seizoen-9_1
2023-12-18 10:15:20.517 T:737864   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/?action=episodesSeason&guid=5d70638e-1a9b-4f34-a890-276f4750ed4d&productId=None&slug=seizoen-9_1) failed2023-12-18 10:15:20.477 T:738135   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '<=' not supported between instances of 'int' and 'NoneType'
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 116, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 106, in router
                                                       items = uzg.getItems(params['action'], params['guid'], params['productId'], params['slug'], text)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 47, in getItems
                                                       return self.episodesOfSeasonItems.getItems(guid)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 121, in getItems
                                                       return JsonToItems.getItems(NpoHelpers.getJsonData(url))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapiclasses.py", line 62, in getItems
                                                       if restriction['available']['from'] <= now <= restriction['available']['till']:
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '<=' not supported between instances of 'int' and 'NoneType'
                                                   -->End of Python script error report<--
                                                   
2023-12-18 10:15:20.512 T:738134   error <general>: GetDirectory - Error getting plugin://plugin.video.uzg/?action=episodesSeason&guid=5d70638e-1a9b-4f34-a890-276f4750ed4d&productId=None&slug=seizoen-9_1
2023-12-18 10:15:20.517 T:737864   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uzg/?action=episodesSeason&guid=5d70638e-1a9b-4f34-a890-276f4750ed4d&productId=None&slug=seizoen-9_1) failed
```
