### ISSUE TITLE
NPO Start - stopped working -  HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ArthurBorsboom** [Opvolger/plugin.video.uzg#63]
Since a couple of days, the NPO Start plugin stopped working for me.
I noticed a 'HTTP 403 Forbidden' in the stacktrace, see below.

Is anybody else experiencing the same issue?

```
2024-08-24 21:12:41.055 T:740     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 403: Forbidden
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 116, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 103, in router
                                                       playVideo(params['productId'])
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/addon.py", line 80, in playVideo
                                                       stream_info, licenseKey = Uzg.getPlayInfo(productId)
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 26, in getPlayInfo
                                                       token = NpoHelpers.getToken(externalId)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 95, in getToken
                                                       response = urlopen(req)
                                                                  ^^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
                                                       return opener.open(url, data, timeout)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 521, in open
                                                       response = meth(req, response)
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
                                                       response = self.parent.error(
                                                                  ^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 559, in error
                                                       return self._call_chain(*args)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
                                                       result = func(*args)
                                                                ^^^^^^^^^^^
                                                     File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   -->End of Python script error report<--
                                                   
2024-08-24 21:12:41.107 T:497     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uzg/?action=play&productId=LI_NL1_4188102&guid=83dc1f25-a065-496c-9418-bd5c60dfb36d&slug=None]
```

**Comment by Opvolger** [comment]
Ik zie dat zoeken op mijn tv het nu ook niet doet. Ik ga dit van de week eens bekijken, het is een beetje druk momenteel :)

**Comment by harmenkets** [comment]
@Opvolger mbt zoeken, ik zie dat ze de query parameter 'query' veranderd hebben naar 'searchQuery', als ik die aanpas in npoapiclasses.py werkt dat weer :+1: .

**Comment by ArthurBorsboom** [comment]
Is het zoekprobleem gerelateerd aan het HTTP 403 Forbidden probleem?
Of zijn dit verschillende issues?

**Comment by Opvolger** [comment]
Dat is het zelfde probleem

**Comment by ArthurBorsboom** [comment]
Hierbij de bevestiging dat de NPO Start plugin weer werkt.
Thanks harmenkets & Bas.
