### ISSUE TITLE
Videos niet meer af te spelen: KeyError: 'token'

### ISSUE THREAD

**Issue by harmenkets** [Opvolger/plugin.video.uzg#64]
Ik heb de json in de logging uitgeprint en de key 'token' blijkt nu 'jwt' te heten, ze zijn bij NPO blijkbaar wat aan het rondschuiven mbt naamgeving.

Hier is de logging vd fout:
````
2024-10-21 14:09:02.034 T:1862    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'token'
                                                   Traceback (most recent call last):
                                                     File "/home/xxxxxxxxx/.kodi/addons/plugin.video.uzg/addon.py", line 117, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/xxxxxxxxx/.kodi/addons/plugin.video.uzg/addon.py", line 104, in router
                                                       playVideo(params['productId'])
                                                     File "/home/xxxxxxxxx/.kodi/addons/plugin.video.uzg/addon.py", line 80, in playVideo
                                                       stream_info, licenseKey = Uzg.getPlayInfo(productId)
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/xxxxxxxxx/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 26, in getPlayInfo
                                                       token = NpoHelpers.getToken(externalId)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/xxxxxxxxx/.kodi/addons/plugin.video.uzg/resources/lib/npoapihelpers.py", line 98, in getToken
                                                       return json.loads(link)['token']
                                                              ~~~~~~~~~~~~~~~~^^^^^^^^^
                                                   KeyError: 'token'
                                                   -->End of Python script error report<--
                                                   
2024-10-21 14:09:02.071 T:1200    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.uzg/?action=play&productId=VPWON_1353487&guid=9c74bc0b-a689-40d6-8d99-0475fb4cbec2&slug=focus_42]
2024-10-21 14:15:58.074 T:1326     info <general>: CActiveAESink::OpenSink - initialize sink````

**Comment by atreyuhere** [comment]
Ik merkte het vandaag ook, er lijkt inderdaad weer of nog geklust te worden

**Comment by Opvolger** [comment]
ik heb het probleem al gevonden!

**Comment by sprintv** [comment]
Bedankt weer.
