### ISSUE TITLE
Video playback stopped working

### ISSUE THREAD

**Issue by g3rb3n** [Opvolger/plugin.video.uzg#9]
Since this morning none of the videos are playable. After checking the logs and adding some debug statements, I figured out that all seems to be working correct except the calls to https://odis.omroep.nl.

Traceback (most recent call last):
  File "uzgtest.py", line 13, in <module>
    print uzg.get_play_url('RKK_1663974')
  File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 83, in get_play_url
    data = self.__get_data_from_url(streamurl)
  File "/home/osmc/.kodi/addons/plugin.video.uzg/resources/lib/uzg.py", line 63, in __get_data_from_url
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

On url https://odis.omroep.nl/video/ida/adaptive/b894eb99e34d49ee4511d5acfa7d2c10/59f5ad89/RKK_1663974/1?extension=m3u8

It might be a temporary failure on odis.

**Comment by jhaand** [comment]
I can confirm. I have the same issue. Both on Libreelec and Android.

**Comment by bbregman** [comment]
I can confirm too, openelec 8.0.4 and kodi 17.3 on rpi2, all videos fail :(

**Comment by deorder** [comment]
Same here. Raspbian/stretch and Kodi 17.4.

**Comment by Opvolger** [comment]
Ik zag ook dat hij het niet meer deed. Zal er binnenkort naar kijken.

**Comment by g3rb3n** [comment]
Net python uzgtest.py uitgevoerd en ik krijg geen foutmeldingen meer. Blijkbaar was er een tijdelijk probleem met de odis server.

**Comment by Opvolger** [comment]
yep, het werkte bij mij ook weer.
